# Generated by Django 5.2.7 on 2025-11-05 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('doctor', 'Doctor')], max_length=20),
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('specialization', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalLeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.TextField(help_text='Describe your symptoms')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('leave_from', models.DateField()),
                ('leave_to', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('doctor_response', models.TextField(blank=True, null=True)),
                ('meeting_link', models.URLField(blank=True, help_text='Google Meet/Zoom link', null=True)),
                ('meeting_scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('medical_certificate', models.FileField(blank=True, null=True, upload_to='medical_certificates/')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='portal.doctor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_leaves', to='portal.student')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
    ]
